site_name: Sieve Documentation

nav:
  - Home: index.md
  - API Quick Start Guide: api_guide.md
  - UI Quick Start Guide: ui_guide.md

theme:
  name: readthedocs
  #custom_dir: docs/overrides
  theme:
    features:
      - toc.integrate

extra_css:
  - style.css